name: Update Package Index

on:
  push:
    branches: [ main ]
    paths:
      - 'manifests/**'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Windows Package Manager
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.6.3482/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile winget.msixbundle
          Add-AppxPackage -Path winget.msixbundle -RegisterByFamilyName
        
      - name: Install PowerShell YAML Module
        shell: pwsh
        run: |
          Install-Module -Name powershell-yaml -Force -Scope CurrentUser
          
      - name: Update Index
        shell: pwsh
        run: |
          $manifestPath = "manifests"
          $indexPath = "index.json"
          
          $currentDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.0000000+00:00")
          
          $index = @{
            Format = "1.0.0"
            Source = @{
              Name = "FOIFA"
              Type = "Microsoft.PreIndexed.Package"
              Identifier = "FOIFA.MainSource"
              SourceUrl = "https://raw.githubusercontent.com/$($env:GITHUB_REPOSITORY)/main/index.json"
              LastUpdate = $currentDate
            }
            Packages = @()
          }
          
          Get-ChildItem -Path $manifestPath -Recurse -Filter "*.yaml" | ForEach-Object {
            if ($_.Name -eq "amneziavpn.yaml") {
              $manifestDir = $_.Directory.FullName
              $manifestContent = Get-Content "$manifestDir\amneziavpn.installer.yaml" | ConvertFrom-Yaml
              $localeContent = Get-Content "$manifestDir\amneziavpn.locale.en-US.yaml" | ConvertFrom-Yaml
              
              $package = @{
                PackageIdentifier = $manifestContent.PackageIdentifier
                PackageVersion = $manifestContent.PackageVersion
                PackageName = $localeContent.PackageName
                Publisher = $localeContent.Publisher
                License = $localeContent.License
                InstallerUrls = @($manifestContent.Installers[0].InstallerUrl)
                InstallerSha256 = $manifestContent.Installers[0].InstallerSha256
                ManifestPath = $manifestDir.Replace($PWD.Path + "\", "").Replace("\", "/")
              }
              
              $index.Packages += $package
            }
          }
          
          $index | ConvertTo-Json -Depth 10 | Set-Content $indexPath
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.json
          git commit -m "Update package index" || exit 0
          git push
