name: Update Package Index

on:
  push:
    branches: [ main ]
    paths:
      - 'manifests/**'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install PowerShell YAML Module
        shell: pwsh
        run: |
          Install-Module -Name powershell-yaml -Force -Scope CurrentUser -SkipPublisherCheck
          
      - name: Generate Index
        shell: pwsh
        run: |
          Import-Module powershell-yaml
          
          $manifestPath = "manifests"
          $indexPath = "index.json"
          
          $currentDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.0000000+00:00")
          
          $index = @{
            Format = "1.0.0"
            Source = @{
              Name = "FOIFA"
              Type = "Microsoft.PreIndexed.Package"
              Identifier = "FOIFA.MainSource"
              SourceUrl = "https://raw.githubusercontent.com/$($env:GITHUB_REPOSITORY)/main/index.json"
              LastUpdate = $currentDate
            }
            Packages = @()
          }
          
          Get-ChildItem -Path $manifestPath -Recurse -Filter "*.yaml" | ForEach-Object {
            if ($_.Name -eq "amneziavpn.yaml") {
              $manifestDir = $_.Directory.FullName
              $installerYaml = Get-Content "$manifestDir\amneziavpn.installer.yaml" -Raw
              $localeYaml = Get-Content "$manifestDir\amneziavpn.locale.en-US.yaml" -Raw
              
              $manifestContent = ConvertFrom-Yaml -Yaml $installerYaml
              $localeContent = ConvertFrom-Yaml -Yaml $localeYaml
              
              $package = @{
                PackageIdentifier = $manifestContent.PackageIdentifier
                PackageVersion = $manifestContent.PackageVersion
                PackageName = $localeContent.PackageName
                Publisher = $localeContent.Publisher
                License = $localeContent.License
                InstallerUrls = @($manifestContent.Installers[0].InstallerUrl)
                InstallerSha256 = $manifestContent.Installers[0].InstallerSha256
                ManifestPath = $manifestDir.Replace($PWD.Path + "\", "").Replace("\", "/")
              }
              
              $index.Packages += $package
            }
          }
          
          $index | ConvertTo-Json -Depth 10 | Set-Content $indexPath
      
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add index.json
          git commit -m "Update package index" || exit 0
          git push origin main
