name: WinGet Create Advanced

on:
  workflow_dispatch:
    inputs:
      packageUrl:
        description: 'URL установщика пакета'
        required: true
      version:
        description: 'Версия пакета'
        required: true

jobs:
  create-and-submit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup WinGet Create
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          echo '{ "telemetry": false }' | Out-File -FilePath "$env:LOCALAPPDATA\Microsoft\WinGet\Create\settings.json" -Encoding UTF8
          .\wingetcreate.exe --version
      
      - name: Create New Package
        run: |
          .\wingetcreate.exe new --url "${{ github.event.inputs.packageUrl }}" --version "${{ github.event.inputs.version }}" --out manifests --silent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
